version: '3'

services:
  app:
    build: .
    ports:
      - 5000:5000
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}
      - PORT=5000
      - NODE_ENV=production
    container_name: helsinki-city-bike-app