version: '3'

services:
  app:
    build: .
    ports:
      - 5000:5000
    environment:
      MONGO_DB: "mongodb://mongodb:27017/helsinki-city-bike-db"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /Users/david/data/db:/data/db

volumes:
  mongodb_data:
