version: '3'

services:
  app:
    build: .
    ports:
      - 5000:5000
    environment:
      - MONGO_DB=mongodb://root:Password1@ec2-54-159-208-255.compute-1.amazonaws.com:27017/helsinki-city-bike-db
      - REACT_APP_SERVER_URL=http://localhost:5000
      - PORT=5000
      - NODE_ENV=production
    container_name: helsinki-city-bike-app