version: '3'

services:
  app:
    image: helsinki-city-bike
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=mongodb://mongo:27017/helsinki-city-bike-db
      - REACT_APP_SERVER_URL=http://localhost:5000
      - PORT=5000
      - NODE_ENV=production
    container_name: helsinki-city-bike-app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /Users/david/data/db:/data/db

volumes:
  mongodb_data:
